// random questions generated by chatgpt. these will be changed soon.

export const data = {
  pages: [
    {
      elements: [
        {
          name: "skincare-routine",
          title: "How would you describe your current skincare routine?",
          type: "radiogroup",
          choices: [
            { value: 5, text: "Extensive and consistent" },
            { value: 4, text: "Fairly consistent, but could improve" },
            { value: 3, text: "Somewhat inconsistent" },
            { value: 2, text: "Rarely follow a routine" },
            { value: 1, text: "No skincare routine" },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "sun-protection",
          title: "How often do you apply sunscreen when going outdoors?",
          type: "radiogroup",
          choices: [
            { value: 5, text: "Always, without fail" },
            { value: 4, text: "Most of the time" },
            { value: 3, text: "Sometimes, when I remember" },
            { value: 2, text: "Rarely, only on sunny days" },
            { value: 1, text: "Never" },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "skin-concerns",
          title: "Do you have any specific concerns about your skin?",
          type: "checkbox",
          choices: [
            { value: "acne", text: "Acne" },
            { value: "dryness", text: "Dryness" },
            { value: "sensitivity", text: "Sensitivity" },
            { value: "aging", text: "Signs of aging" },
            { value: "dark-spots", text: "Dark spots" },
          ],
        },
      ],
    },
    {
      elements: [
        {
          name: "diet",
          title:
            "How would you rate your diet in terms of promoting healthy skin?",
          type: "radiogroup",
          choices: [
            {
              value: 5,
              text: "Excellent, I eat a balanced diet with plenty of fruits and vegetables",
            },
            { value: 4, text: "Good, but could be better" },
            {
              value: 3,
              text: "Average, I try to eat healthy but often indulge in unhealthy foods",
            },
            {
              value: 2,
              text: "Poor, I rarely consider the impact of my diet on my skin",
            },
            { value: 1, text: "Very poor, my diet is mostly unhealthy" },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "hydration-habits",
          title: "How much water do you typically drink in a day?",
          type: "radiogroup",
          choices: [
            { value: 5, text: "More than 8 glasses (64 ounces)" },
            { value: 4, text: "6-8 glasses (48-64 ounces)" },
            { value: 3, text: "4-6 glasses (32-48 ounces)" },
            { value: 2, text: "2-4 glasses (16-32 ounces)" },
            { value: 1, text: "Less than 2 glasses (16 ounces)" },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "stress-management",
          title: "How do you typically manage stress?",
          type: "radiogroup",
          choices: [
            { value: 5, text: "Regular exercise and mindfulness practices" },
            { value: 4, text: "Occasional relaxation techniques" },
            { value: 3, text: "Engagement in hobbies or activities I enjoy" },
            { value: 2, text: "Socializing with friends or family" },
            {
              value: 1,
              text: "Unhealthy coping mechanisms such as smoking or excessive drinking",
            },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "sleep-quality",
          title: "How would you rate the quality of your sleep?",
          type: "radiogroup",
          choices: [
            {
              value: 5,
              text: "Excellent, I consistently get 7-9 hours of restful sleep per night",
            },
            { value: 4, text: "Good, but could improve" },
            {
              value: 3,
              text: "Average, I often experience disturbances or difficulty falling asleep",
            },
            {
              value: 2,
              text: "Poor, I frequently have trouble sleeping or wake up feeling tired",
            },
            { value: 1, text: "Very poor, I struggle to sleep most nights" },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "exercise-habits",
          title: "How often do you engage in physical activity?",
          type: "radiogroup",
          choices: [
            { value: 5, text: "Daily, I have a regular exercise routine" },
            { value: 4, text: "Several times a week" },
            { value: 3, text: "Once or twice a week" },
            { value: 2, text: "Rarely, only on occasion" },
            { value: 1, text: "Never, I lead a sedentary lifestyle" },
          ],
          isRequired: true,
        },
      ],
    },
    {
      elements: [
        {
          name: "allergies",
          title: "Do you have any known allergies or sensitivities?",
          type: "checkbox",
          choices: [
            { value: "pollen", text: "Pollen" },
            { value: "dust", text: "Dust mites" },
            { value: "pets", text: "Pets (e.g., cats, dogs)" },
            { value: "certain-foods", text: "Certain foods" },
            { value: "skincare-products", text: "Skincare products" },
            { value: "medications", text: "Medications" },
          ],
        },
      ],
    },
    {
      elements: [
        {
          name: "dermatological-concerns",
          title:
            "Are there any specific dermatological concerns you'd like to address?",
          type: "comment",
        },
      ],
    },
  ],
  previewText: "Preview answers",
  showPreviewBeforeComplete: "showAnsweredQuestions",
};
